name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  # base-branch:
  #   description: 'Branch to raise pull request against'
  #   required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'